### ISSUE TITLE
if without curly brackets

### ISSUE THREAD

**Issue by Neancence** [smashita/CoffeeMaker-2019#20]
if (userInput == 1) addRecipe();
if (userInput == 2) deleteRecipe();
if (userInput == 3) editRecipe();
if (userInput == 4) addInventory();
if (userInput == 5) checkInventory();
if (userInput == 6) makeCoffee();
if (userInput == 0) System.exit(0);

**Comment by aliadiana** [comment]
if (userInput == 1) {
addRecipe();
}

**Comment by JCNg96** [comment]
if (userInput == 1) {
	addRecipe();
}
if (userInput == 2) {
	deleteRecipe();
}
if (userInput == 3) {
	editRecipe();
}
if (userInput == 4) {
	addInventory();
}
if (userInput == 5) {
	checkInventory();
}
if (userInput == 6) {
	makeCoffee();
}
if (userInput == 0) {
	System.exit(0);
}

**Comment by ThenKimYen** [comment]
if (userInput == 1) {addRecipe();}

if (userInput == 2) {deleteRecipe();}

if (userInput == 3) {editRecipe();}

if (userInput == 4) {addInventory();}

if (userInput == 5) {checkInventory();}

if (userInput == 6) {makeCoffee();}

if (userInput == 0) {System.exit(0);}

**Comment by wajihahmzln** [comment]
if (userInput == 1) {
					addRecipe();
				} else if (userInput == 2) {
					deleteRecipe();
				} else if (userInput == 3) {
					editRecipe();
				} else if (userInput == 4) {
					addInventory();
				} else if (userInput == 5) {
					checkInventory();
				} else if (userInput == 6) {
					makeCoffee();
				} else if (userInput == 0) {
					System.exit(0);
				}

**Comment by LYH977** [comment]
if (userInput == 1) {
addRecipe();
} else if (userInput == 2) {
deleteRecipe();
} else if (userInput == 3) {
editRecipe();
} else if (userInput == 4) {
addInventory();
} else if (userInput == 5) {
checkInventory();
} else if (userInput == 6) {
makeCoffee();
} else if (userInput == 0) {
System.exit(0);
}
