### ISSUE TITLE
WhitespaceAround: 'for' is not followed by whitespace. Empty blocks only be represented as () when no part of multi-block statement (4.1.3) (219:9) [WhitespaceAround]

### ISSUE THREAD

**Issue by AndreaStich** [smashita/CoffeeMaker-2019#25]
for(int i = 0; i < recipes.length; i++) {
        	if (recipes[i] != null) {
        		System.out.println((i+1) + ". " + recipes[i].getName());
        	}
        }

**Comment by Kahyan97** [comment]
sorry but i think you raised issue which title is unrelated to code.

**Comment by AndreaStich** [comment]
for (int i = 0; i < recipes.length; i++) {
        	if (recipes[i] != null) {
        		System.out.println((i+1) + ". " + recipes[i].getName());
        	}
        }
