### ISSUE TITLE
In Recipe.java, from line 171 to 182, the some of the if and else if construct is missing '{ }'

### ISSUE THREAD

**Issue by fungjunyin123** [smashita/CoffeeMaker-2019#26]
Wrong:
if (this == obj)
	return true;
if (obj == null)
	return false;
if (getClass() != obj.getClass())
	return false;
final Recipe other = (Recipe) obj;
if (name == null) {
	if (other.name != null)
		return false;
} else if (!name.equals(other.name))
	return false;

**Comment by CheeHooi97** [comment]
correct:
if (this == obj) {
return true;
}
if (obj == null) {
return false;
}
if (getClass() != obj.getClass()) {
return false;
}
final Recipe other = (Recipe) obj;
if (name == null) {
if (other.name != null) {
return false;
}
} else if (!name.equals(other.name)) {
return false;
}
