### ISSUE TITLE
Line is longer than 100 characters (found 153).

### ISSUE THREAD

**Issue by huiming2T** [smashita/CoffeeMaker-2019#27]
int userInput = Integer.parseInt(inputOutput("Please press the number that corresponds to what you would like the coffee maker to do."));

**Comment by nurinathirah98** [comment]
Based on my reading, keeping 100 chars and below is just considered a good practice, not a rule to follow.  it just enhance the readability.

We can change, through 
window>preferences>java>code formatter>line wrapping> (then change max length)
