### ISSUE TITLE
'member def modifier' has incorrect indentation level 4, expected level should be 2.

### ISSUE THREAD

**Issue by huiming2T** [smashita/CoffeeMaker-2019#29]
Example:
    private String name;
(4 empty space is used at the beginning of declaration of variable)

Solution:
  private String name;
(only 2 empty space is used at the beginning of declaration of variable)

**Comment by CheeHooi97** [comment]
public class Recipe {
////private String name;   // 4 empty space is used at the beginning of declaration of variable

change to

public class Recipe {
//private String name;    // only 2 empty space is used at the beginning of declaration of variable

**Comment by JCNg96** [comment]
These errors can actually be fixed by modifying the settings for indentation. Refer to issue #30
