### ISSUE TITLE
Multiple markers at this line 	- Line contains a tab character. 	- Line is longer than 100 characters (found 106). 	- 'method def' child has incorrect indentation level 12, expected level  	 should be 4.

### ISSUE THREAD

**Issue by huiming2T** [smashita/CoffeeMaker-2019#31]
String chocolateString = inputOutput("\nPlease enter the units of chocolate in the recipe: ");

**Comment by CheeHooi97** [comment]
String chocolateString = inputOutput("\nPlease enter
 the units of chocolate in the recipe: ");
