### ISSUE TITLE
Abbreviation in name 'NUM_RECIPES' must contain no more than '2' consecutive capital letters.

### ISSUE THREAD

**Issue by yeewen0808** [smashita/CoffeeMaker-2019#32]
wrong: private final int NUM_RECIPES = 4;

**Comment by JCNg96** [comment]
Suggest to change to camel case or lower case letters.

**Comment by Kahyan97** [comment]
private final int num_recipes = 4;

**Comment by chihwa97** [comment]
Solution:
private final int NumRecipes = 4;
This is because 'NUM_RECIPES' must contain no more than '2' consecutive capital letters. It should match the pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'.
