### ISSUE TITLE
Member name 'NUM_RECIPES' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'

### ISSUE THREAD

**Issue by JCNg96** [smashita/CoffeeMaker-2019#33]
private final int NUM_RECIPES = 4;

**Comment by huiming2T** [comment]
Solution:
private final int numrecipes = 4;

**Comment by JCNg96** [comment]
'_' underscore is not allowed

**Comment by chihwa97** [comment]
private final int NumRecipes = 4;
This is because 'NUM_RECIPES' should match the pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'.
