### ISSUE TITLE
At-clause should have a non-empty description.

### ISSUE THREAD

**Issue by yeewen0808** [smashita/CoffeeMaker-2019#35]
/**
   * Passes a prompt to the user that deals with the recipe list and returns the user selected
   * number.
   * 
   * @param message
   * @return int
   */

**Comment by JCNg96** [comment]
add description for each line with '@'

**Comment by JCNg96** [comment]
Example:
**@param** message represents prompt message to the user to input number for recipe selection

**Comment by JCNg96** [comment]
/**

Passes a prompt to the user that deals with the recipe list and returns the user selected
number.
@param message represents prompt message to the user to input number for recipe selection
@return int
*/
