### ISSUE TITLE
Lines Longer than 100 and contain Tab character

### ISSUE THREAD

**Issue by AmaniRidzuan98** [smashita/CoffeeMaker-2019#4]
int userInput = Integer.parseInt(inputOutput("Please press the number that corresponds to what you would like the coffee maker to do."));

**Comment by mingliee** [comment]
should be like this?
int userInput = Integer.parseInt(inputOutput("Please press the number that "
     + "corresponds to what you would like the coffee maker to do."));

make one line less than 100

**Comment by huiming2T** [comment]
> should be like this?
> int userInput = Integer.parseInt(inputOutput("Please press the number that "
> + "corresponds to what you would like the coffee maker to do."));
> 
> make one line less than 100

**Comment by huiming2T** [comment]
yes. just make the string less than 100 characters per line. Remove the tab also as there is a mix of tab and empty space used
