### ISSUE TITLE
Block comment has incorrect indentation level 4, expected is 1, (Line 14:0) in CoffeeMaker.java [CommentsIndentation]

### ISSUE THREAD

**Issue by wansyazlina** [smashita/CoffeeMaker-2019#43]
Solution (1 level space)
```
 /**
   * Constructor for the coffee maker
   *
   */
 public CoffeeMaker() {
	    recipeBook = new RecipeBook();
		inventory = new Inventory();
	}
```
- Comments are indented at the same level as the surrounding code. 
-Before this the block comment had 4 level space
- indentation should be same level as "public" which is in line 18

**Comment by LYH977** [comment]
"Block comment has incorrect indentation level 4, expected is 1". It means the line of statement has to be given 1 space character only.
For example('_') represent the space character, 
`_public CoffeeMaker() { }` 
instead of
`____public CoffeeMaker() { }`
