### ISSUE TITLE
overrides java.lang.Object.toString

### ISSUE THREAD

**Issue by izzatisyamimi** [smashita/CoffeeMaker-2019#44]
In the class inventory.java of the coffee maker project, through checkstyle activation, i found an error at public String toString() { ..... (line 235)
It said that its overrides java.lang.Object.toString

The java.lang.Object.toString() method returns a string representation of the object. In general, the toString method returns a string that "textually represents" this object. The result should be a concise but informative representation that is easy for a person to read. It is recommended that all subclasses override this method.

**Comment by fungjunyin123** [comment]
In other words, toString() is actually a built in method in Object class. At line 235, we are creating another toString() method so, an overiding warning is issued.
