### ISSUE TITLE
In Inventory.Java, at line 65  'else' child has incorrect indentation level 24, expected level should be 6 

### ISSUE THREAD

**Issue by ChaiSiuQi** [smashita/CoffeeMaker-2019#50]

**Comment by tongyonghang** [comment]
Like others indentation problem
change 24 empty space to 6 empty space at the beginning of declaration of variable

**Comment by nurinathirah98** [comment]
i dont understand what does it means by change 24 empty space to 6 empty space. is it like move 'else'?

**Comment by tongyonghang** [comment]
For example 
////////////////////////else{ ... } // 24 empty space is used 
change to
//////esle{ ... }   6 empty space
or you can fixed the error by modifying the settings for indentation. Refer to issue #30
