### ISSUE TITLE
Missing JavaDoc Comment 

### ISSUE THREAD

**Issue by nurinathirah98** [smashita/CoffeeMaker-2019#51]
_public void testAddInventory() {
		try {
			cm.addInventory("4","7","0","9");
		} catch (InventoryException e) {
			fail("InventoryException should not be thrown");
		}
	}_

**Comment by nurinathirah98** [comment]
Withoud JavaDoc, it makes much difficult to understand. Javadoc describes what the method does. It should has 

1) desription on pre/post condition
2) Javadoc tag elements that describe any parameters, return value, and thrown exceptions

 Example is like this 

_/**
 * Extracts the user's name from the input arguments.
 *
 * Precondition: 'args' should contain at least one element, the user's name.
 *
 * @param  args            the command-line arguments.
 * @return                 the user's name (the first command-line argument).
 * @throws NoNameException if 'args' contains no element.
 */_

**Comment by nurinathirah98** [comment]
Withoud JavaDoc, it makes much difficult to understand. Javadoc describes what the method does. It should has

desription on pre/post condition
Javadoc tag elements that describe any parameters, return value, and thrown exceptions
Example is like this

_/**
*Extracts the user's name from the input arguments.
*Precondition: 'args' should contain at least one element, the user's name.
* @param args the command-line arguments.
* @return the user's name (the first command-line argument).
* @throws NoNameException if 'args' contains no element.
*/_

**Comment by nurinathirah98** [comment]
Withoud JavaDoc, it makes much difficult to understand. Javadoc describes what the method does. It should has

desription on pre/post condition
Javadoc tag elements that describe any parameters, return value, and thrown exceptions
Example is like this

_/**
*Extracts the user's name from the input arguments.
*Precondition: 'args' should contain at least one element, the user's name.

* (alias) param args the command-line arguments.
*(alias) return the user's name (the first command-line argument).
*(alias) throws NoNameException if 'args' contains no element.
*/_

**Comment by nurinathirah98** [comment]
Withoud JavaDoc, it makes much difficult to understand. Javadoc describes what the method does. It should has

desription on pre/post condition
Javadoc tag elements that describe any parameters, return value, and thrown exceptions
Example is like this

_/**
*Extracts the user's name from the input arguments.
*Precondition: 'args' should contain at least one element, the user's name.

*(alias) param args the command-line arguments.
*(alias) return the user's name (the first command-line argument).
*(alias) throws NoNameException if 'args' contains no element.
*/_

**Comment by mingliee** [comment]
/**
   * Test the function add inventory.
   */
  public void testAddInventory() {
    try {
      cm.addInventory("4","7","0","9");
    } catch (InventoryException e) {
      fail("InventoryException should not be thrown");
    }
  }

-> JavaDoc should begin with /** and end with */
-> Don't forget to put ending period which is full stop "."
