### ISSUE TITLE
 'METHOD_DEF' should be separated from previous statement.

### ISSUE THREAD

**Issue by nurinathirah98** [smashita/CoffeeMaker-2019#52]
In 'recipe.java' line 81 
  public void setAmtMilk(String milk) throws RecipeException{
    	int amtMilk = 0;
    	try {
    		amtMilk = Integer.parseInt(milk);
    	} catch (NumberFormatException e) {
    		throw new RecipeException("Units of milk must be a positive integer");
    	}

**Comment by mingliee** [comment]
=> need to have space between current method and the previous statement which is the javadoc

/**
   * Set the amount of milk.
   * @param milk   The amtMilk to set.
   * @throws RecipeException with exception happens.
   */
 (--spacing--)
  public void setAmtMilk(final String milk) throws RecipeException {
    int amtMilk = 0;
    try {
      amtMilk = Integer.parseInt(milk);
    } catch (NumberFormatException e) {
      throw new RecipeException("Units of milk must be a positive integer");
    }
    if (amtMilk >= 0) {
      this.amtMilk = amtMilk;
    } else {
      throw new RecipeException("Units of milk must be a positive integer");
    }
  }
