### ISSUE TITLE
Parameter message should be final. (276:44) [FinalParameters]

### ISSUE THREAD

**Issue by WongXinYing** [smashita/CoffeeMaker-2019#53]
private static int recipeListSelection(String message) {
    	String userSelection = inputOutput(message);
    	int recipe = 0;
        try {
        	recipe = Integer.parseInt(userSelection) - 1;
        	if (recipe >= 0 && recipe <=2) {
        		System.out.println("Recipe " + recipe);
        	} else {
        		recipe = -1;
        	}
        } catch (NumberFormatException e) {
        	System.out.println("Please select a number from 1-3.");
        	recipe = -1;
        }
        return recipe;
    }

**Comment by ThenKimYen** [comment]
private static int recipeListSelection(final String message) {
String userSelection = inputOutput(message);
int recipe = 0;
try {
recipe = Integer.parseInt(userSelection) - 1;
if (recipe >= 0 && recipe <=2) {
System.out.println("Recipe " + recipe);
} else {
recipe = -1;
}
} catch (NumberFormatException e) {
System.out.println("Please select a number from 1-3.");
recipe = -1;
}
return recipe;
}

**Comment by fungjunyin123** [comment]
The final keyword here is used to ensure that the param 'message' is the same as what has been passed when function is called or to prevent the 'message' from accidentally reset from the method. Consistency is the key point that this issue is regarding.
