### ISSUE TITLE
Abbreviation in name 'NUM_RECIPES' must contain no more than '2' consecutive capital letters.

### ISSUE THREAD

**Issue by LYH977** [smashita/CoffeeMaker-2019#55]
Abbreviation in name 'NUM_RECIPES' must contain no more than '2' consecutive capital letters.	
`private final int NUM_RECIPES = 4;`
change it to
`private final int numRecipes = 4;`

**Comment by badrul-hisham** [comment]
Change it to anything which only have 2 capital letters and without any other symbols
