### ISSUE TITLE
Missing a Javadoc comment.

### ISSUE THREAD

**Issue by LYH977** [smashita/CoffeeMaker-2019#57]
Solution is as below:
` public synchronized boolean addRecipe(Recipe r) {`
change it to

```
  /**
 * addRecipe.
 */
  public synchronized boolean addRecipe(Recipe r) 
```

**Comment by Neancence** [comment]
You add explanation in the comment and write in literature form. For example,
/**
     * The add recipe user interface that process user input.
     */
