### ISSUE TITLE
File Tab Character: Line contains a tab character

### ISSUE THREAD

**Issue by WenFoo97** [smashita/CoffeeMaker-2019#61]
Almost each line in code encounter "File Tab Character: Line contains a tab character" issues.

To solve the problem in Eclipse, 
1) Open Preference > Java > Code Style > Formatter.
22) Click New under Active Profile and give a new Profile Name.
3) Click Edit on your new Active Profile name.
4) Under the "Indention" tab, you will find "Tab Policy".
5) Change the Tab Policy from Mixed to Space only and apply the changes.
6) Navigate to Source > Format  and save.

**Comment by huiming2T** [comment]
use empty space only instead of mix empty space with tab
