### ISSUE TITLE
Indentation: 'method def modifier' has incorrect indentation level 4,   expected level should be 2

### ISSUE THREAD

**Issue by WenFoo97** [smashita/CoffeeMaker-2019#62]
Solve the problem by:
1) Open Preference > Java > Code Style > Formatter.
2) Click Edit.
3) Under the "Indention" tab, you will find "Indentation Size".
4) Reduce the size from 4 to 2.
5) Navigate to Source > Format and save.

**Comment by WenFoo97** [comment]
Only for eclipse

**Comment by huiming2T** [comment]
just delete the 2 empty space before the declaration of method

**Comment by badrul-hisham** [comment]
Error occur because there are empty space present which specifically 2 empty spaces

**Comment by fungjunyin123** [comment]
Right now there is 4 space, so delete 2 space will do the trick

**Comment by WenFoo97** [comment]
This error occur almost in each line. Instead of deleting 2 spaces one by one, using the method above will help u delete 2 space for each line.

**Comment by chandni-ironfort** [comment]
i want 4 indentatio level only. how to disable this warning?

**Comment by OmerAran** [comment]
> i want 4 indentatio level only. how to disable this warning?

if you are using checkstyle, just change your checkstyle.xml file like

```
<module name="Indentation">
            <property name="basicOffset" value="2"/>
            <property name="caseIndent" value="2"/>
            <property name="throwsIndent" value="2"/>
            <property name="arrayInitIndent" value="2"/>
            <property name="lineWrappingIndentation" value="2"/>
        </module> 
```
to
```
<module name="Indentation">
            <property name="basicOffset" value="4"/>
            <property name="caseIndent" value="4"/>
            <property name="throwsIndent" value="4"/>
            <property name="arrayInitIndent" value="4"/>
            <property name="lineWrappingIndentation" value="4"/>
        </module>
```
