### ISSUE TITLE
overrides java.lang.Object.toString

### ISSUE THREAD

**Issue by AmaniRidzuan98** [smashita/CoffeeMaker-2019#63]
i had a problemm to resolve this overrides
public String toString() {
    	StringBuffer buf = new StringBuffer();
    	buf.append("Coffee: ");
    	buf.append(getCoffee());
    	buf.append("\n");
    	buf.append("Milk: ");
    	buf.append(getMilk());
    	buf.append("\n");
    	buf.append("Sugar: ");
    	buf.append(getSugar());
    	buf.append("\n");
    	buf.append("Chocolate: ");
    	buf.append(getChocolate());
    	buf.append("\n");
    	return buf.toString();
    }

**Comment by ainsajidah** [comment]
The default toString() method in Object prints “class name @ hash code”. We can override toString() method in our class to print proper output. In general, it is a good idea to override toString() as we get get proper output when an object is used in print() or println().

**Comment by badrul-hisham** [comment]
It is done so that it return a string representation of an object for others to read is easily.
