### ISSUE TITLE
Problem to 'try' child has incorrect indentation level 16, expected level should be 6.

### ISSUE THREAD

**Issue by ainsajidah** [smashita/CoffeeMaker-2019#64]
try {
    		amtChocolate = Integer.parseInt(chocolate);
    	} catch (NumberFormatException e) {
    		throw new InventoryException("Units of chocolate must be a positive integer");
    	}

**Comment by ElysianitezZuhair** [comment]
For Incorrect Indentation problems
1. Delete all the spaces before the sentences
2. Space to the number of time the expected level should be

For your problem 
The number on the side is the number line used for reference only , not significant.
In step 1 you should make sure 'try' is on the leftmost side, meaning if you backspace it will move up to Line 10.
It should look as follows :

11| try {

In step 2 you have to space the number of time the expected level should be. In your case, it should be 6 times. Thus, you have to add space before 'try' 6 times.
It should look like this :

11 |//////try {

Note : '/' means space
Hope this helps

**Comment by AndrewHii97** [comment]
Refer #37
