### ISSUE TITLE
First sentence should end with a period. (79:0) [JavadocStyle] in (CoffeeMaker.java)

### ISSUE THREAD

**Issue by ThenKimYen** [smashita/CoffeeMaker-2019#68]
`public synchronized String checkInventory() {
        return inventory.toString();
    }
    
    /**
     * Returns the change of a user's beverage purchase, or
     * the user's money if the beverage cannot be made
     * @param r
     * @param amtPaid
     * @return int
     */`

**Comment by Neancence** [comment]
This is caused by the sentence in the comment section does not contain '.' or end with a space. You just need to add '.' in the end of a sentence or remove the space at the end of the sentence to remove the warning.
