### ISSUE TITLE
Bugs: Adding Inventory Error

### ISSUE THREAD

**Issue by JCNg96** [smashita/CoffeeMaker-2019#74]
When add inventory function is triggered, the amount of sugar and chocolate are not added, and an error message: "Inventory was not added". A screenshot is provided below to better describe the error (The initial amount of ingredients are 15 for each).
![image](https://user-images.githubusercontent.com/48374262/70684056-c8c72300-1cdf-11ea-8bcf-931cf8067e67.png)
![image](https://user-images.githubusercontent.com/48374262/70684090-e2686a80-1cdf-11ea-975e-b8b72fbd2299.png)

After adding inventory, checking inventory function returns:
![image](https://user-images.githubusercontent.com/48374262/70684169-2fe4d780-1ce0-11ea-8faa-b0c7bdf01b20.png)
The amount of sugar and chocolate was not added.

**Comment by Neancence** [comment]
![image](https://user-images.githubusercontent.com/57699960/70859535-219cf280-1f50-11ea-9691-a135c1210175.png)

for the addSugar method, there is a **logical error** occured which is the if condition "**amtSugar <= 0**". the **correct** condition should be **"amtSugar >= 0**" as the variable should be a positive value.
