### ISSUE TITLE
Bugs: Delete Recipe Error

### ISSUE THREAD

**Issue by JCNg96** [smashita/CoffeeMaker-2019#75]
Delete recipe function doesn't really delete the entry of recipe in the recipe list. Although the recipe details is deleted from the list, the entry is not deleted. It still shows an empty entry, as shown at the below. Example provided are the list displayed when making coffee:
![image](https://user-images.githubusercontent.com/48374262/70691696-a8559380-1cf4-11ea-947e-c6f776a6e3ae.png)

However, adding another recipe creates a new entry:
![image](https://user-images.githubusercontent.com/48374262/70692324-10f14000-1cf6-11ea-9bb4-1e4238f3442a.png)

This makes the recipe list having an empty entry being shown to the user, user could even select the entry, however, it will cause problem while performing other action like making coffee.

**Comment by ThenKimYen** [comment]
Fixed the bug by bringing forward the recipe array. For example, replacing the deleted recipe with the next recipe class.
`for (int j = recipeToDelete ; j < recipes.length; j++) {
      if(recipes[j] != null) {
        recipes[j] = recipes[j + 1];                      // replace the array with the next array to bring forward the recipe
      }
    }`
