### ISSUE TITLE
Bugs: Recipe name go blank when the recipe is edited.

### ISSUE THREAD

**Issue by JCNg96** [smashita/CoffeeMaker-2019#76]
When the user edited the recipe, the name of the recipe goes blank while the other details are edited and saved.
Before editing:
![image](https://user-images.githubusercontent.com/48374262/70693362-44cd6500-1cf8-11ea-83a6-2612c2c1d658.png)
After editing:
![image](https://user-images.githubusercontent.com/48374262/70693400-59a9f880-1cf8-11ea-99ad-59ed586ebe3b.png)

Possible reason: The system does not ask user to input a new name while editing the recipe and then it takes it as blank/empty string.

**Comment by ThenKimYen** [comment]
Fixed the bug by using set function available in recipe class.
`recipes[recipeToEdit].setPrice(priceString);
      recipes[recipeToEdit].setAmtCoffee(coffeeString);
      recipes[recipeToEdit].setAmtMilk(milkString);
      recipes[recipeToEdit].setAmtSugar(sugarString);
      recipes[recipeToEdit].setAmtChocolate(chocolateString);`
