### ISSUE TITLE
Cannot check inventory 

### ISSUE THREAD

**Issue by badrul-hisham** [smashita/CoffeeMaker-2019#78]
There is a bug when we wanted to check the inventory for the CoffeeMaker. After the addition of new inventory inside the system, the system will not shows the amount of inventory stored inside the system. The system will directly ask our next action after pressing selection number 5.

![view inventory part 1](https://user-images.githubusercontent.com/57698208/70861757-78fd8b80-1f6d-11ea-9145-1c8a4b4a9d4d.PNG)

![view inventory part 2](https://user-images.githubusercontent.com/57698208/70861780-c4b03500-1f6d-11ea-8980-393b3eef36d2.PNG)

**Comment by tongyonghang** [comment]
Please try to pull the latest version of code as check inventory is function properly.
![image](https://user-images.githubusercontent.com/57294615/70980217-e2a4a380-20ed-11ea-9b01-f0fc0cc3a57b.png)
