### ISSUE TITLE
Making coffee bug

### ISSUE THREAD

**Issue by badrul-hisham** [smashita/CoffeeMaker-2019#79]
After adding new recipes into the system, the system can delete as it is one of its features but an error occur when deleting the recipes.  This problem relate to the making coffee features where the user can choose what coffee they wanted to buy. This error shows an empty space where the deleted recipe still shown in the making coffee option 

![buying error part 2 ](https://user-images.githubusercontent.com/57698208/70861869-02fa2400-1f6f-11ea-8c5e-a9c909f934b9.PNG)

**Comment by yeewen0808** [comment]
This bug has already been fixed. 
Check it out at [https://github.com/smashita/CoffeeMaker-2019/issues/75#issue-536813096]

Kindly pull the updated changes from GitHub.
