### ISSUE TITLE
Make coffee bug when there is no recipe inside

### ISSUE THREAD

**Issue by yeewen0808** [smashita/CoffeeMaker-2019#81]
When there is no recipe in CoffeeMaker, the system should notice user in order to avoid the case happens as shown in the figure below.

![image](https://user-images.githubusercontent.com/48169885/70862735-fe3b6d00-1f7a-11ea-8537-6597b3159a6b.png)

**Comment by AndrewHii97** [comment]
Fixed the problem by returning to main menu if recipe is empty
