### ISSUE TITLE
Logical Error for recipeListSelection in Main.java

### ISSUE THREAD

**Issue by AndrewHii97** [smashita/CoffeeMaker-2019#83]
![image](https://user-images.githubusercontent.com/45649830/71002585-8b68f800-211a-11ea-9f73-7f156776c8d8.png)

Logical Error for Input Selection 
Should be able to accept input from number 0 to 3 since the length of the recipe book is 4

**Comment by fungjunyin123** [comment]
simply by changing recipe <= 2 to recipe <= 3 

if (recipe >= 0 && recipe <= 3){
.....
}
