### ISSUE TITLE
missing of '{}' in 'if' construct

### ISSUE THREAD

**Issue by wajihahmzln** [smashita/CoffeeMaker-2019#9]
if (userInput == 1) addRecipe();

	- 'if' construct must use '{}'s.

**Comment by AndrewHii97** [comment]
if (userInput == 1){ addRecipe();}

**Comment by ThenKimYen** [comment]
if (userInput == 1) { addRecipe(); }

**Comment by LYH977** [comment]
if (userInput == 1) {
 addRecipe(); 
}

**Comment by tongyonghang** [comment]
if (userInput == 1) {addRecipe();}

**Comment by zulhaqim1998** [comment]
if (userInput == 1) {
    addRecipe();
}

**Comment by badrul-hisham** [comment]
if (userInput == 1) {
addRecipe();
}

**Comment by AmaniRidzuan98** [comment]
if (userInput == 1) {addRecipe();}
